- name: Add node repo
  become: yes
  yum_repository:
    name: nodejs
    description: nodejs repo
    baseurl: https://rpm.nodesource.com/pub_7.x/el/6/x86_64/
    gpgcheck: no

- name: Install nodejs
  become: yes
  yum:
   name: nodejs-{{node_version}}
   state: latest

